('Abde Ezzalzouli', 'Real Betis'),
('Abde Rebbach', 'Deportivo Alavés'),
('Abdel Abqar', 'Deportivo Alavés'),
('Abdoulaye Keita', 'Getafe Cf'),
('Abdul Mumin', 'Rayo Vallecano'),
('Abdón Prats', 'Rcd Mallorca'),
('Abel Bretones', 'Ca Osasuna'),
('Abel Ruiz', 'Girona Fc'),
('Aboubacar Bassinga', 'Cd Mirandés'),
('Adama Boiro', 'Athletic Club'),
('Adnan Januzaj', 'Ud Las Palmas'),
('Adri Embarba', 'Rayo Vallecano'),
('Adrià Alti', 'Cd Leganés'),
('Adrià Pedrosa', 'Sevilla Fc'),
('Adrián San Miguel Del Castillo', 'Real Betis'),
('Adrián Arnu', 'Real Valladolid Cf'),
('Adrián Hernández Hernández', 'Deportivo Alavés'),
('Adrián Rodríguez', 'Deportivo Alavés'),
('Malcom Abdulai Ares Djaló', 'Real Zaragoza'),
('Aihen Muñoz', 'Real Sociedad'),
('Álvaro Killane', 'Ud Las Palmas'),
('Álvaro Odriozola', 'Real Sociedad'),
('Álvaro Rodríguez', 'Getafe Cf'),
('Álvaro Tejero', 'Rcd Espanyol De Barcelona'),
('Ángel Correa', 'Atlético De Madrid'),
('Ángel Fortuño', 'Rcd Espanyol De Barcelona'),
('Áron Yaakobishvili', 'Fc Barcelona'),
('Éder Gabriel Militão', 'Real Madrid'),
('Íñigo Lekue', 'Athletic Club'),
('Íñigo Ruíz De Galarreta', 'Athletic Club'),
('Óscar De Marcos', 'Athletic Club'),
('Óscar Mingueza', 'Rc Celta'),
('Óscar Rodríguez', 'Cd Leganés'),
('Óscar Trejo', 'Rayo Vallecano'),
('Óscar Valentín', 'Rayo Vallecano'),
('Ørjan Nyland', 'Sevilla Fc'),
('Yeremy Pino', 'Villarreal Cf'),
('Yoel Lago', 'Rc Celta'),
('Youssef Lekhedim', 'Real Madrid'),
('Youssouf Sabaly', 'Real Betis'),
('Yuri Berchiche', 'Athletic Club'),
('Yvan Neyou', 'Cd Leganés'),
('Yáser Asprilla', 'Girona Fc'),
('Álex Baena', 'Villarreal Cf'),
('Álex Gil', ''),
('Álex Muñoz', 'Ud Las Palmas'),
('Álex Remiro', 'Real Sociedad'),
('Álex Sola', 'Getafe Cf'),
('Álex Suárez', 'Ud Las Palmas'),
('Álex Valle', ''),
('Álvaro Aceves', 'Real Valladolid Cf'),
('Álvaro Aguado', 'Rcd Espanyol De Barcelona'),
('Álvaro Cortés', 'Fc Barcelona'),
('Álvaro Djaló Dias Fernandes', 'Athletic Club'),
('Álvaro Fernández', 'Sevilla Fc'),
('Álvaro García', 'Rayo Vallecano'),
('Valery Fernández', 'Rcd Mallorca'),
('Vedat Muriqi', 'Rcd Mallorca'),
('Vicente Guaita', 'Rc Celta'),
('Viktor Tsyhankov', 'Girona Fc'),
('Vinícius José Paixão De Oliveira Júnior', 'Real Madrid'),
('Viti Rozada', 'Ud Las Palmas'),
('Vitor Hugo Roque Ferreira', 'Real Betis'),
('Víctor Meseguer', 'Real Valladolid Cf'),
('Víctor Muñoz Villanueva', 'Real Madrid'),
('Víctor Puig', 'Ud Las Palmas'),
('Walid Cheddira', 'Rcd Espanyol De Barcelona'),
('Warren Madrigal', 'Valencia Cf'),
('William Silva De Carvalho', 'Real Betis'),
('Williot Swedberg', 'Rc Celta'),
('Willy Kambwala', 'Villarreal Cf'),
('Wojciech Szczesny', 'Fc Barcelona'),
('Yangel Herrera', 'Girona Fc'),
('Yarek Gasiorowski', 'Valencia Cf'),
('Jesús Santiago Pérez', 'Getafe Cf'),
('Yeray Álvarez', 'Athletic Club'),
('Thierno Barry', 'Villarreal Cf'),
('Thierry Rendall Correia', 'Valencia Cf'),
('Thomas Lemar', 'Atlético De Madrid'),
('Tomás Conechny', 'Deportivo Alavés'),
('Toni Fernández', 'Fc Barcelona'),
('Antonio Latorre Grueso', 'Rcd Mallorca'),
('Toni Martínez', 'Deportivo Alavés'),
('Laureano Antonio Villa Suárez', 'Sd Eibar'),
('Umar Sadiq', 'Real Sociedad'),
('Unai Egiluz', 'Cd Mirandés'),
('Unai García', 'Ca Osasuna'),
('Unai Gómez', 'Athletic Club'),
('Unai López', 'Rayo Vallecano'),
('Unai Marrero', 'Real Sociedad'),
('Unai Núñez', 'Athletic Club'),
('Unai Simón', 'Athletic Club'),
('Urko González', 'Real Sociedad'),
('Valentin Rosier', 'Cd Leganés'),
('Valentín Barco', 'Sevilla Fc'),
('Valentín Pezzolesi', 'Ud Las Palmas'),
('Sergio Herrera', 'Ca Osasuna'),
('Sergio Mestre', 'Real Madrid'),
('Seydouba Cissé', 'Cd Leganés'),
('Sheraldo Becker', 'Real Sociedad'),
('Siebe Van Der Heyden', 'Rcd Mallorca'),
('Silvi Clua', 'Girona Fc'),
('Stanis Idumbo Muzambo', 'Sevilla Fc'),
('Stanko Juric', 'Real Valladolid Cf'),
('Stipe Biuk', ''),
('Juan Diego Molina Martínez', 'Deportivo Alavés'),
('Stole Dimitrievski', 'Valencia Cf'),
('Jesús Joaquín Fernández Sáenz De La Torre', 'Sevilla Fc'),
('Sébastien Haller', 'Cd Leganés'),
('Tadeo Allende', 'Rc Celta'),
('Takefusa Kubo', 'Real Sociedad'),
('Takuma Asano', 'Rcd Mallorca'),
('Tanguy Nianzou', 'Sevilla Fc'),
('Tasos Douvikas', 'Rc Celta'),
('Thiago Ojeda', 'Villarreal Cf'),
('Thibaut Courtois', 'Real Madrid'),
('Samuel Dias Lino', 'Atlético De Madrid'),
('Samuel De Almeida Costa', 'Rcd Mallorca'),
('Sandro Ramírez', 'Ud Las Palmas'),
('Santi Comesaña', 'Villarreal Cf'),
('Santiago Mouriño', 'Deportivo Alavés'),
('Saúl Ñíguez', 'Sevilla Fc'),
('Scott Mckenna', 'Ud Las Palmas'),
('Sebas Wade', 'Rcd Mallorca'),
('Selim Amallah', 'Real Valladolid Cf'),
('Sergi Altimira', 'Real Betis'),
('Sergi Canós', 'Valencia Cf'),
('Sergi Cardona', 'Villarreal Cf'),
('Sergi Darder', 'Rcd Mallorca'),
('Sergi Domínguez', 'Fc Barcelona'),
('Sergi Guardiola', 'Rayo Vallecano'),
('Sergi Gómez', 'Rcd Espanyol De Barcelona'),
('Sergio Camello', 'Rayo Vallecano'),
('Sergio Carreira', 'Rc Celta'),
('Sergio González', 'Cd Leganés'),
('Sergio Gómez', 'Real Sociedad'),
('Renato Tapia', 'Cd Leganés'),
('Ricard Artero', 'Girona Fc'),
('Ricardo Rodríguez', 'Real Betis'),
('Robert Lewandowski', 'Fc Barcelona'),
('Robert Navarro', 'Rcd Mallorca'),
('Roberto López', 'Cd Leganés'),
('Robin Le Normand', 'Atlético De Madrid'),
('Rodrigo Sánchez Rodríguez', ''),
('Rodrigo Abajas', 'Valencia Cf'),
('Rodrigo De Paul', 'Atlético De Madrid'),
('Rodrigo Riquelme', 'Atlético De Madrid'),
('Rodrygo Silva De Goes', 'Real Madrid'),
('Romain Perraud', 'Real Betis'),
('Ronald Araujo', 'Fc Barcelona'),
('Rubén García', 'Ca Osasuna'),
('Rubén Gómez', 'Villarreal Cf'),
('Rubén Iranzo', 'Valencia Cf'),
('Rubén Peña', 'Ca Osasuna'),
('Rui Tiago Dantas Da Silva', 'Real Betis'),
('Salvi Sánchez', 'Rcd Espanyol De Barcelona'),
('Peter Federico González Carmona', 'Getafe Cf'),
('Pol Lozano', 'Rcd Espanyol De Barcelona'),
('Pol Tristán', 'Rcd Espanyol De Barcelona'),
('Cristian Portugués Manzanera', 'Girona Fc'),
('Rafa Mir', 'Valencia Cf'),
('Rafael Bauza', 'Rcd Espanyol De Barcelona'),
('Rafael Romero', 'Sevilla Fc'),
('Ramon Terrats', 'Villarreal Cf'),
('Ramón Martínez', 'Sevilla Fc'),
('Randy Nteka', 'Rayo Vallecano'),
('Raphael Dias Belloli', 'Fc Barcelona'),
('Raúl Asencio Del Rosario', 'Real Madrid'),
('Raúl Albiol', 'Villarreal Cf'),
('Raúl Chasco', 'Real Valladolid Cf'),
('Raúl García', 'Ca Osasuna'),
('Raúl Jiménez', 'Valencia Cf'),
('Raúl Martínez', 'Girona Fc'),
('Raúl Moro', 'Real Valladolid Cf'),
('Raúl De Tomás', 'Rayo Vallecano'),
('Reinildo Isnard Mandava', 'Atlético De Madrid'),
('Papa Dame Ba', 'Girona Fc'),
('Pape Gueye', 'Villarreal Cf'),
('Pathé Ciss', 'Rayo Vallecano'),
('Pau Cabanes', 'Villarreal Cf'),
('Pau Cubarsí', 'Fc Barcelona'),
('Pau López', 'Girona Fc'),
('Pau Navarro', 'Villarreal Cf'),
('Pau Víctor', 'Fc Barcelona'),
('Paulo Gazzaniga', 'Girona Fc'),
('Pedro González López', 'Fc Barcelona'),
('Pedro Díaz', 'Rayo Vallecano'),
('Pedro Ortiz', 'Sevilla Fc'),
('Peio Canales', 'Athletic Club'),
('Francisco Jesús Crespo García', 'Ud Las Palmas'),
('Pelayo Fernández', 'Rayo Vallecano'),
('Pep Chavarría', 'Rayo Vallecano'),
('José Luis García Vayá', 'Valencia Cf'),
('Gerard Fernández Castellano', 'Sevilla Fc'),
('Pere García', 'Rcd Mallorca'),
('Pere Milla', 'Rcd Espanyol De Barcelona'),
('Noah Darvich', 'Fc Barcelona'),
('Nobel Mendy', 'Real Betis'),
('Oier Gastesi', 'Athletic Club'),
('Oihan Sancet', 'Athletic Club'),
('Oliver Mcburnie', 'Ud Las Palmas'),
('Omar Alderete', 'Getafe Cf'),
('Omar El Hilali', 'Rcd Espanyol De Barcelona'),
('Omar Mascarell', 'Rcd Mallorca'),
('Omar Sadik', 'Rcd Espanyol De Barcelona'),
('Oriol Romeu', 'Girona Fc'),
('Orri Óskarsson', 'Real Sociedad'),
('Pablo Barrios', 'Atlético De Madrid'),
('Pablo Busto', 'Real Betis'),
('Pablo Durán', 'Rc Celta'),
('Pablo Fornals', 'Real Betis'),
('Pablo Ibáñez', 'Ca Osasuna'),
('Pablo Maffeo', 'Rcd Mallorca'),
('Pablo Marín', 'Real Sociedad'),
('Pablo Rivera', 'Sevilla Fc'),
('Pablo Torre', 'Fc Barcelona'),
('Mika Mármol', 'Ud Las Palmas'),
('Mikel Jauregizar', 'Athletic Club'),
('Mikel Oyarzabal', 'Real Sociedad'),
('Mikel Vesga', 'Athletic Club'),
('Moi Gómez', 'Ca Osasuna'),
('Moussa Diarra', 'Deportivo Alavés'),
('Munir El Haddadi', 'Cd Leganés'),
('Nabil Aberdin', 'Getafe Cf'),
('Nabil Fekir', ''),
('Nacho Vidal', 'Ca Osasuna'),
('Naci Ünüvar', 'Rcd Espanyol De Barcelona'),
('Nahuel Molina', 'Atlético De Madrid'),
('Nahuel Tenaglia', 'Deportivo Alavés'),
('Naim García', 'Cd Leganés'),
('Natan Bernardo De Souza', 'Real Betis'),
('Nayef Aguerd', 'Real Sociedad'),
('Nemanja Gudelj', 'Sevilla Fc'),
('Nico Serrano', 'Athletic Club'),
('Nicholas Williams Arthuer', 'Athletic Club'),
('Nicolas Pépé', 'Villarreal Cf'),
('Marcos Llorente', 'Atlético De Madrid'),
('Marcos Do Nascimento Teixeira', 'Sevilla Fc'),
('Mario Maroto', 'Real Valladolid Cf'),
('Mario Martín', 'Real Valladolid Cf'),
('Marko Dmitrovic', 'Cd Leganés'),
('Martin Valjent', 'Rcd Mallorca'),
('Martín Tejón', 'Valencia Cf'),
('Martín Zubimendi', 'Real Sociedad'),
('Marvin Park', 'Ud Las Palmas'),
('Mateo Flores', 'Real Betis'),
('Mateo Mejía', 'Sevilla Fc'),
('Mateu Morey', 'Rcd Mallorca'),
('Matija Nastasic', 'Cd Leganés'),
('Matías Árbol', 'Sevilla Fc'),
('Mauro Arambarri', 'Getafe Cf'),
('Maximiliano Caufriez', 'Valencia Cf'),
('Miguel Gutiérrez', 'Girona Fc'),
('Miguel De La Fuente', 'Cd Leganés'),
('Miguel Ángel Morro', ''),
('Mihailo Ristic', 'Rc Celta'),
('Luka Romero', 'Deportivo Alavés'),
('Luka Sucic', 'Real Sociedad'),
('Mamadou Sylla', 'Real Valladolid Cf'),
('Manu Bueno', 'Sevilla Fc'),
('Manu Fuster', 'Ud Las Palmas'),
('Manu González', 'Real Betis'),
('Manu Morlanes', 'Rcd Mallorca'),
('Manu Sánchez', 'Deportivo Alavés'),
('Marash Kumbulla', 'Rcd Espanyol De Barcelona'),
('Marc Bartra', 'Real Betis'),
('Marc Bernal', 'Fc Barcelona'),
('Marc Cardona', 'Ud Las Palmas'),
('Marc Casadó', 'Fc Barcelona'),
('Marc Domenech', 'Rcd Mallorca'),
('Marc Roca', 'Real Betis'),
('Marc Vidal', 'Rc Celta'),
('Marc-André Ter Stegen', 'Fc Barcelona'),
('Marco De Las Sias', 'Rayo Vallecano'),
('Marcos Alonso', 'Rc Celta'),
('Marcos André De Sousa Mendonça', 'Real Valladolid Cf'),
('Lamine Yamal Nasraoui Ebana', 'Fc Barcelona'),
('Leandro Cabrera', 'Rcd Espanyol De Barcelona'),
('Leo Román', 'Rcd Mallorca'),
('Llorenç Serred', 'Rcd Espanyol De Barcelona'),
('Logan Evans Costa', 'Villarreal Cf'),
('Lorenzo Aguado Herrera', 'Real Madrid'),
('Loïc Badé', 'Sevilla Fc'),
('Luca De La Torre', 'Rc Celta'),
('Lucas Alcázar', 'Real Betis'),
('Lucas García Madrigal', 'Girona Fc'),
('Lucas Ocampos', ''),
('Lucas Oliveira Rosa', 'Real Valladolid Cf'),
('Lucas Torró', 'Ca Osasuna'),
('Lucas Vázquez', 'Real Madrid'),
('Lucien Agoumé', 'Sevilla Fc'),
('Luis Milla', 'Getafe Cf'),
('Luis Pérez', 'Real Valladolid Cf'),
('Luis Rioja', 'Valencia Cf'),
('Luiz Lúcio Reis Júnior', 'Villarreal Cf'),
('Luka Modric', 'Real Madrid'),
('Jules Koundé', 'Fc Barcelona'),
('Julián Álvarez', 'Atlético De Madrid'),
('Julián Chicco', 'Cd Leganés'),
('Juma Bah', 'Real Valladolid Cf'),
('Justin Smith', 'Rcd Espanyol De Barcelona'),
('Karl Hein', 'Real Valladolid Cf'),
('Kelechi Iheanacho', 'Sevilla Fc'),
('Robert Kenedy Nunes Do Nascimento', 'Real Valladolid Cf'),
('Kike Barja', 'Ca Osasuna'),
('Kike García', 'Deportivo Alavés'),
('Kike Pérez', 'Real Valladolid Cf'),
('Kike Salas', 'Sevilla Fc'),
('Kiko Femenía', 'Villarreal Cf'),
('Min-Su Kim', 'Girona Fc'),
('Kirian Rodríguez', 'Ud Las Palmas'),
('Jorge Iglesias González', 'Real Valladolid Cf'),
('Jorge Resurrección Merodio', 'Atlético De Madrid'),
('Kylian Mbappé', 'Real Madrid'),
('Ladislav Krejcí', 'Girona Fc'),
('Lalo Aguilar', 'Albacete Bp'),
('José Giménez', 'Atlético De Madrid'),
('José Ángel Carmona', 'Sevilla Fc'),
('João Urbáez', 'Cd Leganés'),
('Juan Bernat', 'Villarreal Cf'),
('Juan Berrocal', 'Getafe Cf'),
('Juan Carlos Martín Corral', 'Girona Fc'),
('Juan Cruz', 'Cd Leganés'),
('Juan Cruz Álvaro Armada', 'Ca Osasuna'),
('Juan Foyth', 'Villarreal Cf'),
('Juan Herzog', 'Ud Las Palmas'),
('Juan Iglesias', 'Getafe Cf'),
('Juan Musso', 'Atlético De Madrid'),
('Juan Soriano', 'Cd Leganés'),
('Juanlu Sánchez', 'Sevilla Fc'),
('Juan Miguel Jiménez López', 'Real Betis'),
('Juanmi Latasa', 'Real Valladolid Cf'),
('Juan Pedro Ramírez López', 'Girona Fc'),
('Jude Bellingham', 'Real Madrid'),
('Julen Agirrezabala', 'Athletic Club'),
('Julen Lartitegi', 'Deportivo Alavés'),
('Johan Mojica', 'Rcd Mallorca'),
('John Patrick', 'Getafe Cf'),
('Johnny Cardoso', 'Real Betis'),
('Jon Aramburu', 'Real Sociedad'),
('Jon Guridi', 'Deportivo Alavés'),
('Jon Magunazelaia', 'Real Sociedad'),
('Jon Martín', 'Real Sociedad'),
('Jon Moncayola', 'Ca Osasuna'),
('Jon Olasagasti', 'Real Sociedad'),
('Jon Pacheco', 'Real Sociedad'),
('Jonathan Bamba', 'Rc Celta'),
('Joni Montiel', 'Rayo Vallecano'),
('Jorge Herrando', 'Ca Osasuna'),
('Jorge Sáenz', 'Cd Leganés'),
('Jorge De Frutos', 'Rayo Vallecano'),
('Joseph Aidoo', 'Rc Celta'),
('José Arnáiz', 'Ca Osasuna'),
('José Campaña', 'Ud Las Palmas'),
('José Gayà', 'Valencia Cf'),
('José Gragera', 'Rcd Espanyol De Barcelona'),
('Javi Muñoz', 'Ud Las Palmas'),
('Javi Puado', 'Rcd Espanyol De Barcelona'),
('Javi Rodríguez', 'Rc Celta'),
('Javi Serrano', 'Atlético De Madrid'),
('Javi Sánchez De Felipe', 'Real Valladolid Cf'),
('Javier Manquillo', 'Rc Celta'),
('Javier Martón', 'Athletic Club'),
('Jesús Areso', 'Ca Osasuna'),
('Jesús Navas', 'Sevilla Fc'),
('Jesús Owono', 'Deportivo Alavés'),
('Jesús Rodriguez', 'Real Betis'),
('Jesús Vallejo', 'Real Madrid'),
('Jesús Vázquez', 'Valencia Cf'),
('Jhon Solís', 'Girona Fc'),
('Jirí Letácek', 'Getafe Cf'),
('Joan García', 'Rcd Espanyol De Barcelona'),
('Joan Jordán', 'Deportivo Alavés'),
('Joaquín Panichelli', 'Cd Mirandés'),
('Joel Roca', 'Cd Mirandés'),
('Jofre Carreras', 'Rcd Espanyol De Barcelona'),
('Ignacio Peña Sotorres', 'Fc Barcelona'),
('Iñaki Rupérez', 'Real Sociedad'),
('Iñaki Williams', 'Athletic Club'),
('Íñigo Martínez', 'Fc Barcelona'),
('Jackson Porozo', 'Cd Leganés'),
('Jacobo Ramón', 'Real Madrid'),
('Jailson Marques Siqueira', 'Rc Celta'),
('Jaime Mata', 'Ud Las Palmas'),
('James Rodríguez', 'Rayo Vallecano'),
('Jan Oblak', 'Atlético De Madrid'),
('Jan Salas', 'Rcd Mallorca'),
('Jasper Cillessen', 'Ud Las Palmas'),
('Antonino Jastin García López', 'Girona Fc'),
('Jaume Domènech', 'Valencia Cf'),
('Javi Galán', 'Atlético De Madrid'),
('Javi Guerra', 'Valencia Cf'),
('Javi Hernández', 'Cd Leganés'),
('Javi Llabrés', 'Rcd Mallorca'),
('Javi López', 'Real Sociedad'),
('Javi Martínez', 'Ca Osasuna'),
('Iker Bachiller', 'Cd Leganés'),
('Iker Benito', 'Ca Osasuna'),
('Iker Córdoba', 'Valencia Cf'),
('Iker Losada', 'Real Betis'),
('Iker Muñoz', 'Ca Osasuna'),
('Iker Álvarez', 'Villarreal B'),
('Moriba Kourouma Kourouma', 'Rc Celta'),
('Ilias Akhomach', 'Villarreal B'),
('Ilias Kostis', 'Atlético De Madrid'),
('Irvin Cardona', 'Rcd Espanyol De Barcelona'),
('Isaac Romero', 'Sevilla Fc'),
('Francisco Román Alarcón Suárez', 'Real Betis'),
('Isi Palazón', 'Rayo Vallecano'),
('Israel Domínguez', 'Sevilla Fc'),
('Iván Balliu', 'Rayo Vallecano'),
('Iván Cuéllar', 'Rcd Mallorca'),
('Iván Gil', 'Ud Las Palmas'),
('Iván Martín', 'Girona Fc'),
('Iván Sánchez Aguayo', 'Real Valladolid Cf'),
('Iván Villar', 'Rc Celta'),
('Giovani Lo Celso', 'Real Betis'),
('Giuliano Simeone', 'Atlético De Madrid'),
('Gonzalo García', 'Real Madrid'),
('Gonzalo Montiel', 'Sevilla Fc'),
('Gorka Guruzeta', 'Athletic Club'),
('Gorka Rivera', 'Getafe Cf'),
('Guille Fernández', 'Fc Barcelona'),
('Guillem Trilla', 'Getafe Cf'),
('Hamari Traoré', 'Real Sociedad'),
('Horatiu Moldovan', ''),
('Hugo Duro', 'Valencia Cf'),
('Hugo Guillamón', 'Valencia Cf'),
('Hugo Novoa', 'Deportivo Alavés'),
('Hugo Sotelo', 'Rc Celta'),
('Hugo Álvarez', 'Rc Celta'),
('Héctor Bellerín', 'Real Betis'),
('Héctor Fort', 'Fc Barcelona'),
('Iago Aspas', 'Rc Celta'),
('Igor Zubeldia', 'Real Sociedad'),
('Iker Almena', ''),
('Ferran Torres', 'Fc Barcelona'),
('Ferrán Ruiz Martí', 'Girona Fc'),
('Florian Lejeune', 'Rayo Vallecano'),
('Fran Beltrán', 'Rc Celta'),
('Fran García', 'Real Madrid'),
('Francisco Javier González Pérez', 'Real Madrid'),
('Fran Pérez', 'Valencia Cf'),
('Francisco Barbosa Vieites', 'Real Betis'),
('Franco Cervi', 'Rc Celta'),
('Frenkie De Jong', 'Fc Barcelona'),
('Fábio Daniel Soares Silva', 'Ud Las Palmas'),
('Gabriel Misehouy', 'Girona Fc'),
('Álvaro Miguel García Pascual', 'Sevilla Fc'),
('Pablo Páez Gavira', 'Fc Barcelona'),
('Gerard Gumbau', 'Rayo Vallecano'),
('Gerard Martín', 'Fc Barcelona'),
('Gerard Moreno', 'Villarreal Cf'),
('Germán Valera', 'Valencia Cf'),
('Gerónimo Spina', 'Atlético De Madrid'),
('Giorgi Mamardashvili', 'Valencia Cf'),
('Egoitz Muñoz', 'Deportivo Alavés'),
('Endrick Felipe Moreira De Sousa', 'Real Madrid'),
('Eneko Ortiz', 'Deportivo Alavés'),
('Enric Franquesa', 'Cd Leganés'),
('Enric García', 'Girona Fc'),
('Enzo Barrenechea', 'Valencia Cf'),
('Enzo Boyomo', 'Ca Osasuna'),
('Enzo Loiodice', 'Ud Las Palmas'),
('Eray Cömert', 'Real Valladolid Cf'),
('Eric Bailly', 'Villarreal Cf'),
('Eric García', 'Fc Barcelona'),
("Etienne Eto'O Pineda", 'Rayo Vallecano'),
('Karl Edouard Blaise Etta Eyong', 'Villarreal Cf'),
('Fabio González', 'Ud Las Palmas'),
('Federico Valverde', 'Real Madrid'),
('Ferland Mendy', 'Real Madrid'),
('Fermín López', 'Fc Barcelona'),
('Fernando Calero', 'Rcd Espanyol De Barcelona'),
('Fernando López', 'Rc Celta'),
('Fernando Pacheco', 'Rcd Espanyol De Barcelona'),
('Diego Ferrer', 'Getafe Cf'),
('Diego García', 'Cd Leganés'),
('Diego Kochen', 'Fc Barcelona'),
('Diego Llorente', 'Real Betis'),
('Diego López', 'Valencia Cf'),
('Diego Rico', 'Getafe Cf'),
('Dimitri Foulquier', 'Valencia Cf'),
('Dimitrios Stamatakis', 'Ca Osasuna'),
('Dinko Horkas', 'Ud Las Palmas'),
('Djené Dakonam', 'Getafe Cf'),
('Djibril Sow', 'Sevilla Fc'),
('Djordjije Medenica', 'Getafe Cf'),
('Dodi Lukébakio', 'Sevilla Fc'),
('Domingos De Sousa Coutinho Meneses Duarte', 'Getafe Cf'),
('Dominik Greif', 'Rcd Mallorca'),
('Donny Van De Beek', 'Girona Fc'),
('Dário Cassia Luís Essugo', 'Ud Las Palmas'),
('Edu Expósito', 'Rcd Espanyol De Barcelona'),
('Eduardo Camavinga', 'Real Madrid'),
('Egoitz Arana', 'Real Sociedad'),
('Dani Parejo', 'Villarreal Cf'),
('Dani Raba', 'Cd Leganés'),
('Dani Requena', 'Villarreal Cf'),
('Dani Rodríguez', 'Rcd Mallorca'),
('Dani Vivian', 'Athletic Club'),
('Daniel Luna', 'Rcd Mallorca'),
('Daniel Yáñez', 'Real Madrid'),
('Darko Brasanac', 'Cd Leganés'),
('Darwin Machís', 'Real Valladolid Cf'),
('Darío Benavides', 'Sevilla Fc'),
('David Argüelles', 'Getafe Cf'),
('David Jiménez', 'Real Madrid'),
('David López', 'Girona Fc'),
('David Otorbi', 'Valencia Cf'),
('David Soria', 'Getafe Cf'),
('David Torres', 'Real Valladolid Cf'),
('Dawda Camara', 'Girona Fc'),
('Denis Suárez', 'Villarreal Cf'),
('Diego Aguado Facio', 'Real Madrid'),
('Diego Conde', 'Villarreal Cf'),
('Clément Lenglet', 'Atlético De Madrid'),
('Coba Da Costa', 'Getafe Cf'),
('Conor Gallagher', 'Atlético De Madrid'),
('José Manuel Arias Copete', 'Rcd Mallorca'),
('Cristhian Mosquera', 'Valencia Cf'),
('Cristhian Stuani', 'Girona Fc'),
('Cyle Larin', 'Rcd Mallorca'),
('Cédric Bakambu', 'Real Betis'),
('César Azpilicueta', 'Atlético De Madrid'),
('César Fernández', 'Rc Celta'),
('César Tárrega', 'Valencia Cf'),
('César De La Hoz', 'Real Valladolid Cf'),
('Daley Blind', 'Girona Fc'),
('Daley Sinkgraven', 'Ud Las Palmas'),
('Damián Rodríguez', 'Rc Celta'),
('Dani Carvajal', 'Real Madrid'),
('Dani Ceballos', 'Real Madrid'),
('Dani Cárdenas', 'Rayo Vallecano'),
('Dani Gómez', 'Valencia Cf'),
('Dani Olmo', 'Fc Barcelona'),
('Brian Oliván', 'Rcd Espanyol De Barcelona'),
('Bryan Gil', 'Girona Fc'),
('Bryan Zaragoza', 'Ca Osasuna'),
('Carl Starfelt', 'Rc Celta'),
('Carles Aleñá', 'Getafe Cf'),
('Carles Pérez', 'Getafe Cf'),
('Carlos Benavídez', 'Deportivo Alavés'),
('Carlos Domínguez', 'Rc Celta'),
('Carlos Guirao', 'Real Betis'),
('Carlos Martín', 'Deportivo Alavés'),
('Carlos Romero', 'Rcd Espanyol De Barcelona'),
('Carlos Vicente', 'Deportivo Alavés'),
('José Luis Català Vázquez', 'Rcd Espanyol De Barcelona'),
('Cenk Özkacar', 'Real Valladolid Cf'),
('José María Andres Baixauli', 'Real Madrid'),
('Chidera Ejuke', 'Sevilla Fc'),
('Chimy Ávila', 'Real Betis'),
('Francisco Jorge Tavares Oliveira', 'Rcd Mallorca'),
('Christantus Uche', 'Getafe Cf'),
('Iván Cantalejo', 'Real Valladolid Cf'),
('Arnau Martínez', 'Girona Fc'),
('Arnau Rafús', 'Real Valladolid Cf'),
('Arnau Solà', 'Villarreal Cf'),
('Arnaut Danjuma', 'Girona Fc'),
('Arthur Vermeeren', 'Rb Leipzig'),
('Asier Villalibre', 'Deportivo Alavés'),
('Assane Diao', 'Real Betis'),
('Augusto Batalla', 'Rayo Vallecano'),
('Aurélien Tchouaméni', 'Real Madrid'),
('Axel Witsel', 'Atlético De Madrid'),
('Ayoze Pérez', 'Villarreal Cf'),
('Benito Ramírez', 'Ud Las Palmas'),
('Bertug Yildirim', 'Getafe Cf'),
('Beñat Prados', 'Athletic Club'),
('Beñat Turrientes', 'Real Sociedad'),
('Bojan Miovski', 'Girona Fc'),
('Borja Iglesias', 'Rc Celta'),
('Borja Mayoral', 'Getafe Cf'),
('Brahim Díaz', 'Real Madrid'),
('Brais Méndez', 'Real Sociedad'),
('Domingos André Ribeiro Almeida', 'Valencia Cf'),
('André Filipe Magalhães Ribeiro Ferreira', 'Real Valladolid Cf'),
('Andrés Cuenca', 'Fc Barcelona'),
('Ansu Fati', 'Fc Barcelona'),
('Ante Budimir', 'Ca Osasuna'),
('Antoine Griezmann', 'Atlético De Madrid'),
('Antonio Blanco', 'Deportivo Alavés'),
('Antonio Espigares', 'Villarreal Cf'),
('Antonio Gomis', 'Atlético De Madrid'),
('Antonio Raíllo', 'Rcd Mallorca'),
('Antonio Rüdiger', 'Real Madrid'),
('Antonio Sivera', 'Deportivo Alavés'),
('Antonio Sánchez', 'Rcd Mallorca'),
('Antoniu Roca', 'Rcd Espanyol De Barcelona'),
('Anuar Tuhami', 'Real Valladolid Cf'),
('Arda Güler', 'Real Madrid'),
('Aridane Hernández', 'Rayo Vallecano'),
('Aritz Arambarri', 'Sd Eibar'),
('Aritz Elustondo', 'Real Sociedad'),
('Arkaitz Mariezkurrena', 'Real Sociedad'),
('Domingos André Ribeiro Almeida', 'Valencia Cf'),
('André Filipe Magalhães Ribeiro Ferreira', 'Real Valladolid Cf'),
('Andrés Cuenca', 'Fc Barcelona'),
('Ansu Fati', 'Fc Barcelona'),
('Ante Budimir', 'Ca Osasuna'),
('Antoine Griezmann', 'Atlético De Madrid'),
('Antonio Blanco', 'Deportivo Alavés'),
('Antonio Espigares', 'Villarreal Cf'),
('Antonio Gomis', 'Atlético De Madrid'),
('Antonio Raíllo', 'Rcd Mallorca'),
('Antonio Rüdiger', 'Real Madrid'),
('Antonio Sivera', 'Deportivo Alavés'),
('Antonio Sánchez', 'Rcd Mallorca'),
('Antoniu Roca', 'Rcd Espanyol De Barcelona'),
('Anuar Tuhami', 'Real Valladolid Cf'),
('Arda Güler', 'Real Madrid'),
('Aridane Hernández', 'Rayo Vallecano'),
('Aritz Arambarri', 'Sd Eibar'),
('Aritz Elustondo', 'Real Sociedad'),
('Arkaitz Mariezkurrena', 'Real SociedadDomingos André Ribeiro Almeida , Valencia Cf'),
('André Filipe Magalhães Ribeiro Ferreira', 'Real Valladolid Cf'),
('Andrés Cuenca', 'Fc Barcelona'),
('Ansu Fati', 'Fc Barcelona'),
('Ante Budimir', 'Ca Osasuna'),
('Antoine Griezmann', 'Atlético De Madrid'),
('Antonio Blanco', 'Deportivo Alavés'),
('Antonio Espigares', 'Villarreal Cf'),
('Antonio Gomis', 'Atlético De Madrid'),
('Antonio Raíllo', 'Rcd Mallorca'),
('Antonio Rüdiger', 'Real Madrid'),
('Antonio Sivera', 'Deportivo Alavés'),
('Antonio Sánchez', 'Rcd Mallorca'),
('Antoniu Roca', 'Rcd Espanyol De Barcelona'),
('Anuar Tuhami', 'Real Valladolid Cf'),
('Arda Güler', 'Real Madrid'),
('Aridane Hernández', 'Rayo Vallecano'),
('Aritz Arambarri', 'Sd Eibar'),
('Aritz Elustondo', 'Real Sociedad'),
('Arkaitz Mariezkurrena', 'Real Sociedad'),
('Domingos André Ribeiro Almeida', 'Valencia Cf'),
('André Filipe Magalhães Ribeiro Ferreira', 'Real Valladolid Cf'),
('Andrés Cuenca', 'Fc Barcelona'),
('Ansu Fati', 'Fc Barcelona'),
('Ante Budimir', 'Ca Osasuna'),
('Antoine Griezmann', 'Atlético De Madrid'),
('Antonio Blanco', 'Deportivo Alavés'),
('Antonio Espigares', 'Villarreal Cf'),
('Antonio Gomis', 'Atlético De Madrid'),
('Antonio Raíllo', 'Rcd Mallorca'),
('Antonio Rüdiger', 'Real Madrid'),
('Antonio Sivera', 'Deportivo Alavés'),
('Antonio Sánchez', 'Rcd Mallorca'),
('Antoniu Roca', 'Rcd Espanyol De Barcelona'),
('Anuar Tuhami', 'Real Valladolid Cf'),
('Arda Güler', 'Real Madrid'),
('Aridane Hernández', 'Rayo Vallecano'),
('Aritz Arambarri', 'Sd Eibar'),
('Aritz Elustondo', 'Real Sociedad'),
('Arkaitz Mariezkurrena', 'Real Sociedad'),
